name: Continuous Integration

on: [pull_request]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 15.2.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.2.x'
      - name: Install dependencies
        run: npm ci && npm install @angular/cli@11.0.2
      - name: Build
        run: ng build --prod --sourceMap=false --base-href /cicd-pipeline-angular/
      - name: Test
        run: ng test --watch=false --code-coverage --source-map true
      # - name: Archive build
      #   if: success()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: deploy_dist
      #     path: dist
      # - name: Archive code coverage result
      #   if: success()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: deploy_coverage
      #     path: coverage
    # name: Build and Test
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v1

    #   - name: Install Dependencies
    #     run: yarn

    #   - name: Build
    #     run: yarn build

    #   - name: Test
    #     run: yarn test --watchAll=false